//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DirectoryBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Id { get; set; }

        [Display(Name = "Telephone")]
        [StringLength(20, MinimumLength = 12, ErrorMessage = "The string length must be between 12 and 20 characters")]
        public string Tel { get; set; }

        [Display(Name = "Additional Information")]
        public string Additional_Information { get; set; }

        public Nullable<int> PersonId { get; set; }
    
        public virtual Name Name { get; set; }
    }
}
